#ifndef __GLIMPSE_RETVAL_H__
#define __GLIMPSE_RETVAL_H__
#include <glimpse/future.h>
#include <glimpse/def.h>
#define GLIMPSE_ESUCCESS 0
#define GLIMPSE_EINVAILDARG -1
#define GLIMPSE_ETOOMANYAPI -2
#define GLIMPSE_ETOOMANYTG -2
#define GLIMPSE_EMEMORYLIMIT -2
#define GLIMPSE_ENOTFOUND -3
#define GLIMPSE_ESYMNOTFOUND -4
#define GLIMPSE_EUNKNOWN -5
#define GLIMPSE_EMALFORMEDAPI -6
#define GLIMPSE_EINVALIDVERCODE -7
#define GLIMPSE_EDEPEND -8
#define GLIMPSE_EVERSION -9
#define GLIMPSE_EMAILFORMEDTG -10
#define GLIMPSE_ENOSYMBOL -11
#define GLIMPSE_EDUPSYMBOL -12
#define GLIMPSE_ELISTFULL -13
#endif
